/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aerolinea;

import edu.uci.ics.jung.graph.DirectedGraph;
import edu.uci.ics.jung.graph.DirectedSparseMultigraph;
import edu.uci.ics.jung.graph.util.EdgeType;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Random;
import java.util.Scanner;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Inspiron
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    private TDAGraph grafo;
    private Queue<String> ciudades;
    private ArrayList caminos;
    private ArrayList numeros;
    private int fila;
    private DirectedGraph<Viaje, Arista> Grafo;
    private int menor = 160;
    private int precioTotal = 0;

    public main() {
        initComponents();
        this.setLocationRelativeTo(this);
        panelRuta.setEnabled(false);
        agregarPasaje.setEnabled(false);
        hastaComboBox.setEnabled(false);
        ciudades = new LinkedList<String>();
        grafo = new TDAGraph();
        comprar.setEnabled(false);
        agregarPasaje2.setEnabled(false);
        cargarComboBoxs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAgregado = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        labelRuta = new javax.swing.JLabel();
        panelRuta = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        comprar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        vueloDirectoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        desdeComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        hastaComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCalcular = new javax.swing.JTable();
        agregarPasaje = new javax.swing.JButton();
        vueloIndirectoPanel = new javax.swing.JPanel();
        vueloDirectoPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        desdeComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        hastaComboBox2 = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        escalas = new javax.swing.JTable();
        buscar = new javax.swing.JButton();
        agregarPasaje2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("AEROLINEA");

        tablaAgregado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aereolinea", "Desde", "Para", "Precio", "Pasajes", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaAgregado);

        jButton2.setText("Ver todas las Rutas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        labelRuta.setText("Ruta:");

        javax.swing.GroupLayout panelRutaLayout = new javax.swing.GroupLayout(panelRuta);
        panelRuta.setLayout(panelRutaLayout);
        panelRutaLayout.setHorizontalGroup(
            panelRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRutaLayout.createSequentialGroup()
                .addGap(0, 466, Short.MAX_VALUE)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRutaLayout.setVerticalGroup(
            panelRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRutaLayout.createSequentialGroup()
                .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        comprar.setText("Comprar");

        jLabel1.setText("Desde:");

        desdeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desdeComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Hasta:");

        hastaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaComboBoxActionPerformed(evt);
            }
        });

        tablaCalcular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aereolinea", "Desde", "Para", "Precio", "Boletos Disponibles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCalcularMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCalcular);

        agregarPasaje.setText("Agregar Pasaje");
        agregarPasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPasajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vueloDirectoPanelLayout = new javax.swing.GroupLayout(vueloDirectoPanel);
        vueloDirectoPanel.setLayout(vueloDirectoPanelLayout);
        vueloDirectoPanelLayout.setHorizontalGroup(
            vueloDirectoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vueloDirectoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vueloDirectoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(vueloDirectoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(desdeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(hastaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(agregarPasaje)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        vueloDirectoPanelLayout.setVerticalGroup(
            vueloDirectoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vueloDirectoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vueloDirectoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(desdeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(hastaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarPasaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vuelos Directos", vueloDirectoPanel);

        jLabel4.setText("Desde:");

        desdeComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desdeComboBox2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Hasta:");

        hastaComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaComboBox2ActionPerformed(evt);
            }
        });

        escalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aereolinea", "Desde", "Para", "Precio", "Boletos Disponibles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        escalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escalasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(escalas);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        agregarPasaje2.setText("Agregar Pasaje");
        agregarPasaje2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPasaje2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vueloDirectoPanel1Layout = new javax.swing.GroupLayout(vueloDirectoPanel1);
        vueloDirectoPanel1.setLayout(vueloDirectoPanel1Layout);
        vueloDirectoPanel1Layout.setHorizontalGroup(
            vueloDirectoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vueloDirectoPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vueloDirectoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vueloDirectoPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(desdeComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(hastaComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(agregarPasaje2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vueloDirectoPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        vueloDirectoPanel1Layout.setVerticalGroup(
            vueloDirectoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vueloDirectoPanel1Layout.createSequentialGroup()
                .addGroup(vueloDirectoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hastaComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(desdeComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(buscar)
                    .addComponent(agregarPasaje2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout vueloIndirectoPanelLayout = new javax.swing.GroupLayout(vueloIndirectoPanel);
        vueloIndirectoPanel.setLayout(vueloIndirectoPanelLayout);
        vueloIndirectoPanelLayout.setHorizontalGroup(
            vueloIndirectoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vueloIndirectoPanelLayout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(vueloDirectoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        vueloIndirectoPanelLayout.setVerticalGroup(
            vueloIndirectoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vueloIndirectoPanelLayout.createSequentialGroup()
                .addComponent(vueloDirectoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vuelo Indirecto", vueloIndirectoPanel);

        jLabel6.setText("Total:");

        total.setText("$ 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(167, 167, 167))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelRuta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comprar)
                    .addComponent(jLabel6)
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRuta)
                    .addComponent(panelRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hastaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaComboBoxActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaCalcular.getModel();
        while (tablaCalcular.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        try {
            File archivo = new File(".\\Precio.txt");
            FileReader fileReader = new FileReader(archivo);
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            String temporal, desde, hacia, precio, aereolinea;
            StringTokenizer tokens = null;
            while ((temporal = bufferedReader.readLine()) != null) {
                tokens = new StringTokenizer(temporal, "@");
                while (tokens.hasMoreTokens()) {
                    aereolinea = tokens.nextToken();
                    desde = tokens.nextToken();
                    hacia = tokens.nextToken();
                    precio = tokens.nextToken();
                    if (desde.equals(desdeComboBox.getSelectedItem())
                            && hacia.equals(hastaComboBox.getSelectedItem())) {
                        double p = Double.parseDouble(precio);
                        Object[] data = {aereolinea, desde, hacia, p, random()};
                        modelo.addRow(data);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            //JOptionPane.showMessageDialog(null, "No se pueden cargar los vertices");
        }
    }//GEN-LAST:event_hastaComboBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Grafo = new DirectedSparseMultigraph<>();

        try {
            File Archivo = new File(".\\lugares.txt");
            Scanner E = new Scanner(Archivo);
            while (E.hasNext()) {
                String[] NewLine = E.nextLine().split("@");
                Viaje R1 = new Viaje(NewLine[0], "Test");
                Viaje R2 = new Viaje(NewLine[1], "Test");

                Viaje Vertex1 = checkNode(R1);
                Viaje Vertex2 = checkNode(R2);

                if (Vertex1 == null) {
                    Grafo.addVertex(R1);
                    Vertex1 = R1;
                }
                if (Vertex2 == null) {
                    Grafo.addVertex(R2);
                    Vertex2 = R2;
                }

                Arista Edge = new Arista(Grafo.getEdgeCount() + 1, Double.parseDouble(NewLine[2]));

                Grafo.addEdge(Edge, Vertex1, Vertex2);
            }
        } catch (Exception e) {

        }
        Graficar g = new Graficar();
        g.paintGraph(Grafo);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void desdeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desdeComboBoxActionPerformed
        // TODO add your handling code here:
        hastaComboBox.removeAllItems();
        hastaComboBox.setEnabled(true);
        String seleccionado = (String) desdeComboBox.getSelectedItem();
        try {
            File archivo = new File(".\\Precio.txt");
            FileReader fileReader = new FileReader(archivo);
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            String temporal, desde, hacia, precio, aereolinea;
            StringTokenizer tokens = null;
            while ((temporal = bufferedReader.readLine()) != null) {
                tokens = new StringTokenizer(temporal, "@");
                while (tokens.hasMoreTokens()) {
                    aereolinea = tokens.nextToken();
                    desde = tokens.nextToken();
                    hacia = tokens.nextToken();
                    precio = tokens.nextToken();
                    if (desde.equals(seleccionado)) {
                        hastaComboBox.addItem(hacia);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "No se pueden cargar los vertices");
        }
    }//GEN-LAST:event_desdeComboBoxActionPerformed

    private void tablaCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCalcularMouseClicked
        // TODO add your handling code here:
        setFila(tablaCalcular.getSelectedRow());
        agregarPasaje.setEnabled(true);
    }//GEN-LAST:event_tablaCalcularMouseClicked

    private void agregarPasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPasajeActionPerformed
        // TODO add your handling code here:
        int boletos = (Integer) tablaCalcular.getValueAt(fila, 4);
        if (boletos <= 0) {
            JOptionPane.showMessageDialog(this, "No hay boletos dispoibles para este vuelo");
        } else {
            try {
                int cant = Integer.parseInt(JOptionPane.showInputDialog("Ingrese cantidad de boletos: "));
                if (cant > boletos) {
                    JOptionPane.showMessageDialog(this, "No hay esa cantidad de boletos disponibles");
                } else {
                    DefaultTableModel modelo = (DefaultTableModel) tablaAgregado.getModel();
                    String aereolinea = (String) tablaCalcular.getValueAt(fila, 0);
                    String desde = (String) tablaCalcular.getValueAt(fila, 1);
                    String hacia = (String) tablaCalcular.getValueAt(fila, 2);
                    double p = (double) tablaCalcular.getValueAt(fila, 3);
                    Object[] data = {aereolinea, desde, hacia, p, cant,p*cant};
                    modelo.addRow(data);
                    precioTotal += p * cant;
                    total.setText("$ " + precioTotal);
                }
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_agregarPasajeActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        ciudades.add((String) desdeComboBox2.getSelectedItem());
        ciudades.add((String) hastaComboBox2.getSelectedItem());
        if (!ciudades.isEmpty()) {
            caminos = grafo.calcularCamino(ciudades);
            DefaultTableModel modelo = (DefaultTableModel) escalas.getModel();
            while (escalas.getRowCount() > 0) {
                modelo.removeRow(0);
            }
            String[] arreglo = caminos.get(0).toString().split("-");
            int cont = 0, cont1 = 1, cont2 = 2, cont3 = 3;
            System.out.println(arreglo.length);
            for (int i = 0; i < arreglo.length / 4; i++) {
                System.out.println("cont:" + cont + "cont3:" + cont3);
                String aereolinea = arreglo[cont];
                String desde = arreglo[cont2];
                String hacia = arreglo[cont3];
                double p = Double.parseDouble(arreglo[cont1]);
                int cant = random();

                if (menor < cant) {
                    menor = cant;
                }
                Object[] data = {aereolinea, desde, hacia, p, cant};
                modelo.addRow(data);
                cont += 4;
                cont1 += 4;
                cont2 += 4;
                cont3 += 4;
            }
            agregarPasaje2.setEnabled(true);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void desdeComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desdeComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desdeComboBox2ActionPerformed

    private void hastaComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hastaComboBox2ActionPerformed

    private void escalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escalasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_escalasMouseClicked

    private void agregarPasaje2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPasaje2ActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(JOptionPane.showInputDialog("Cuantos boletos desea comprar?"));
        if (num > menor) {
            JOptionPane.showMessageDialog(this, "No hay suficientes boletos");
        } else {
            DefaultTableModel modelo = (DefaultTableModel) tablaAgregado.getModel();
            String desde = (String) desdeComboBox2.getSelectedItem();
            String hasta = (String) hastaComboBox2.getSelectedItem();
            double precio = Double.parseDouble(caminos.get(1).toString());
            Object[] data = {"*SCALAS*", desde, hasta, precio, num, precio * num};
            modelo.addRow(data);
            precioTotal += precio * num;
            total.setText("$ " + precioTotal);
        }
    }//GEN-LAST:event_agregarPasaje2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    private void cargarCombobox() {
        desdeComboBox.removeAllItems();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPasaje;
    private javax.swing.JButton agregarPasaje2;
    private javax.swing.JButton buscar;
    private javax.swing.JButton comprar;
    private javax.swing.JComboBox desdeComboBox;
    private javax.swing.JComboBox desdeComboBox2;
    private javax.swing.JTable escalas;
    private javax.swing.JComboBox hastaComboBox;
    private javax.swing.JComboBox hastaComboBox2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelRuta;
    private javax.swing.JPanel panelRuta;
    private javax.swing.JTable tablaAgregado;
    private javax.swing.JTable tablaCalcular;
    private javax.swing.JLabel total;
    private javax.swing.JPanel vueloDirectoPanel;
    private javax.swing.JPanel vueloDirectoPanel1;
    private javax.swing.JPanel vueloIndirectoPanel;
    // End of variables declaration//GEN-END:variables
    private void cargarComboBoxs() {
        desdeComboBox.removeAllItems();
        try {
            File archivo = new File(".\\Vertices.txt");
            FileReader fileReader = new FileReader(archivo);
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            String temporal, desde;
            while ((temporal = bufferedReader.readLine()) != null) {
                desdeComboBox.addItem(temporal);
                desdeComboBox2.addItem(temporal);
                hastaComboBox2.addItem(temporal);
            }
        } catch (Exception e) {

        }
    }

    public int getFila() {
        return fila;
    }

    public void setFila(int fila) {
        this.fila = fila;
    }

    private int random() {
        Random numero = new Random();
        int n = 0 + numero.nextInt(160);
        return n;
    }

    private Viaje checkNode(Viaje R) {
        Viaje[] arrayViaje = Grafo.getVertices().toArray(new Viaje[0]);
        for (int i = 0; i < arrayViaje.length; i++) {
            if (arrayViaje[i].equals(R)) {
                return arrayViaje[i];
            }
        }
        return null;
    }

}
